version: "3"
services:
  postgres-wtt:
    image: postgres
    container_name: docker-postgres-treedb
    ports:
      - "5432:5432"
    build:
      context: ./wtt_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trees3r4t
      - POSTGRES_DB=postgres
      - DB_NAME=treedb
      - DB_USER=trees
      - DB_PASSWORD=trees3r4t
    restart: unless-stopped
    volumes:
      - ./wtt_db/treedb.sql:/docker-entrypoint-initdb.d/treedb.sql
  wtt_server:
    container_name: wtt_server
    depends_on:
      - 'postgres-wtt'
    ports:
      - "3002:3002"
    environment:
      - DATABASE_HOST=${HOST_IP}
      - DATABASE_PORT=${PSQL_PORT}
    volumes: # allows for live changes to reflect in container
      - ./wtt_server:/usr/src/app # all local files are mirrored Docker
      - /usr/src/app/node_modules # ignores local node_modules folder
    build: ./wtt_server
  wtt_front:
    container_name: wtt_front
    depends_on:
      - 'postgres-wtt'
    ports:
      - "3000:3000"
    volumes:
     - ./wtt_front:/usr/src/app
     - /usr/src/app/node_modules
    build: ./wtt_front
