version: "3"
services:
  wtt_postgis:
    image: postgis/postgis
    container_name: wtt_postgis
    ports:
      - "5432:5432"
    build:
      context: ./wtt_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trees3r4t
      - POSTGRES_DB=postgres
      - DB_NAME=treedb
      - DB_USER=trees
      - DB_PASSWORD=trees3r4t
    restart: unless-stopped
    volumes:
      - ./wtt_db/treedb.sql:/docker-entrypoint-initdb.d/treedb.sql
      - ./wtt_db:/usr/src/app # all local files are mirrored Docker
      - /usr/src/app/node_modules # ignores local node_modules folder
    networks:
      - waterthetrees
  # wtt_server:
  #   container_name: wtt_server
  #   depends_on:
  #     - 'wtt_postgis'
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - DATABASE_HOST=wtt_postgis
  #     - DATABASE_PORT=5432
  #   volumes: # allows for live changes to reflect in container
  #     - ./wtt_server:/usr/src/app # all local files are mirrored Docker
  #     - /usr/src/app/node_modules # ignores local node_modules folder
  #   build: ./wtt_server
  #   networks:
  #     - waterthetrees
  # wtt_front:
  #    container_name: wtt_front
  #    depends_on:
  #      - 'wtt_postgis'
  #    ports:
  #      - 3000:3000
  #    volumes:
  #     - ./wtt_front:/usr/src/app
  #     - /usr/src/app/node_modules
  #    build: ./wtt_front
  #   networks:
  #     - waterthetrees

networks:
  waterthetrees:
    # external: true
    driver: bridge
    # aliases:
    #   - waterthetrees
    #   - wtt
